IBM/cp4waiops-gitops

README.md
docs/customization-install.md

@gyliu513 Could you please take a look and add some comments ?
Issue: https://github.com/cloud-pak-gitops/cp4waiops-gitops/issues/19
Fixed #19

Add Customization Install readme

---

docs/how-to-deploy-cp4waiops-32.md

Add  argocd permissions in README

Grant argocd permissions

---

config/3.2/cp4waiops/templates/ai-crd.yaml
config/3.2/cp4waiops/templates/ai-installation.yaml
config/3.2/cp4waiops/templates/ai-patch-serviceaccount.yaml
config/3.2/cp4waiops/templates/ai-subscription.yaml
config/3.2/cp4waiops/templates/catalogsource.yaml
config/3.2/cp4waiops/templates/image-pull-secret.yaml
config/3.2/cp4waiops/templates/noi-crd.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-crd.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-sa.yaml
config/3.2/cp4waiops/templates/noi-eventmanager.yaml
config/3.2/cp4waiops/templates/noi-serviceaccount.yaml
config/3.2/cp4waiops/templates/noi-subscription.yaml
config/3.2/cp4waiops/templates/operatorgroup.yaml
config/3.2/cp4waiops/templates/policy.yaml
config/3.2/cp4waiops/values.yaml
docs/how-to-deploy-cp4waiops-32.md

Enable install event manager
Fixed https://github.com/cloud-pak-gitops/cp4waiops-gitops/issues/23

Add eventmanager install

---

config/3.2/cp4waiops/templates/noi-subscription.yaml

Remove startingCSV in subscription and use the default latest CSV version

remove startingCSV

---

config/3.2/cp4waiops/templates/00-argocd-admin.yaml
config/3.2/cp4waiops/templates/ai-image-pull-secret.yaml
config/3.2/cp4waiops/templates/ai-installation.yaml
config/3.2/cp4waiops/templates/ai-ns.yaml
config/3.2/cp4waiops/templates/ai-operatorgroup.yaml
config/3.2/cp4waiops/templates/ai-patch-serviceaccount.yaml
config/3.2/cp4waiops/templates/ai-subscription.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-crd.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-sa.yaml
config/3.2/cp4waiops/templates/noi-eventmanager.yaml
config/3.2/cp4waiops/templates/noi-image-pull-secret.yaml
config/3.2/cp4waiops/templates/noi-ns.yaml
config/3.2/cp4waiops/templates/noi-operatorgroup.yaml
config/3.2/cp4waiops/templates/noi-serviceaccount.yaml
config/3.2/cp4waiops/templates/noi-subscription.yaml
config/3.2/cp4waiops/templates/policy.yaml
config/3.2/cp4waiops/values.yaml

Deploy AIManager and Event Manager under different namespace.
Verified by pengbo in luban.
Fixed: #41

use diff ns for ai and noi

---

config/3.2/cp4waiops/templates/00-argocd-admin.yaml
config/3.2/cp4waiops/templates/catalogsource.yaml
config/3.2/cp4waiops/templates/noi-crd.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-crd.yaml
config/3.2/cp4waiops/templates/noi-diffing-customization-sa.yaml
config/3.2/cp4waiops/templates/noi-eventmanager.yaml
config/3.2/cp4waiops/templates/noi-image-pull-secret.yaml
config/3.2/cp4waiops/templates/noi-ns.yaml
config/3.2/cp4waiops/templates/noi-operatorgroup.yaml
config/3.2/cp4waiops/templates/noi-serviceaccount.yaml
config/3.2/cp4waiops/templates/noi-subscription.yaml
config/3.2/cp4waiops/templates/policy.yaml
config/3.2/cp4waiops/values.yaml
docs/how-to-deploy-cp4waiops-32.md

Change name from eventManagerGateway to eventManager, need add eventManagerGateway installation later.
Fixed #42

Change name to eventManager

---

config/3.1/argocd-apps/infra/values.yaml
docs/how-to-deploy-airgap-32.md
docs/how-to-deploy-cp4waiops-31.md
docs/how-to-deploy-cp4waiops-32.md

Moved repo to IBM org

---

docs/advanced-install.md

update advanced install

---

docs/how-to-create-local-registry.md

Updated local registry

---

config/3.2/airgap/portableImageCopy/Chart.yaml
config/3.2/airgap/portableImageCopy/templates/00-argocd-admin.yaml
config/3.2/airgap/portableImageCopy/templates/copy-image.yaml
config/3.2/airgap/portableImageCopy/templates/ns.yaml
config/3.2/airgap/portableImageCopy/values.yaml
docs/how-to-deploy-airgap-32.md

Add portableImageCopy job in Portable compute device and Portable storage device.
Fixed #47

Add portableImageCopy job

---

config/3.2/cp4waiops/templates/noi-eventmanager.yaml

Fix invalid YAML in eventmanger cr yaml

Fix invalid YAML

---

config/all-in-one/templates/cluster-operator-fyre.yaml
config/all-in-one/templates/clusters-fyre.yaml
config/all-in-one/values.yaml
config/clusters/fyre/templates/ocp-plus.yaml
config/clusters/fyre/templates/qb-large.yaml
config/clusters/fyre/values.yaml
docs/deploy-ocp-cloudpak-with-gitops.md

Add OCP+ support in ocp proviosn template

Add OCP+ support in ocp proviosn template

---

README.md
docs/README.md
docs/how-to-deploy-cp4waiops.md

- fix doc issues
- remove instructions for releases other than 3.4

Br update3.4 doc

---

config/cp-shared/operators/Chart.yaml
config/cp4waiops/install-aimgr/Chart.yaml
config/cp4waiops/install-emgr/Chart.yaml

update chart versions

---

.github/workflows/release.yaml

update flow folder

---

config/cp4waiops/install-aimgr/Chart.yaml
config/cp4waiops/install-emgr/Chart.yaml

chart version update to 3.4.0

---

README.md
docs/README.md
mkdocs.yml

update docs for 3.4

---

mkdocs.yml

Signed-off-by: chuan <huangch@cn.ibm.com>

ghpage update tbd

---

index.yaml

Update index.yaml 

---

docs/how-to-deploy-cp4waiops-daily-build.md

update biuld repo info

---

docs/how-to-deploy-cp4waiops-daily-build.md

updat format

---

docs/how-to-deploy-cp4waiops-daily-build.md

adding repo credential test

---

README.md
docs/how-to-deploy-cp4waiops.md

Update docs to release 3.5

---

docs/how-to-deploy-cp4waiops.md
mkdocs.yml

update for ghpages version and doc links

Update docs gitpages

---

docs/README.md
docs/how-to-deploy-cp4waiops-36.md

update docs for 3.6

---

docs/how-to-deploy-cp4waiops-36.md

Signed-off-by: Chuan Huang <huangch@cn.ibm.com>

update bullets test

---

config/all-in-one/Chart.yaml
config/all-in-one/templates/aimanager.yaml
config/all-in-one/templates/argocd.yaml
config/all-in-one/templates/clusters-fyre.yaml
config/all-in-one/templates/cp-shared.yaml
config/all-in-one/templates/cp4waiops-custom.yaml
config/all-in-one/templates/eventmanager.yaml
config/all-in-one/templates/rook-ceph.yaml
config/all-in-one/values.yaml
config/cp-shared/operators/Chart.yaml

Signed-off-by: Huang Chuan <huangch@cn.ibm.com>

update version numbers

---

docs/how-to-deploy-cp4waiops-35.md
docs/how-to-deploy-cp4waiops-36.md

Signed-off-by: Louise Roberts <louiseroberts@uk.ibm.com>
https://github.ibm.com/katamari/dev-issue-tracking/issues/43196

Docs - suggestions from Louise

---

config/all-in-one/templates/cp-shared.yaml

Signed-off-by: Huang Chuan <huangch@cn.ibm.com>

cpshared-app-set

---

docs/how-to-deploy-cp4waiops-35.md
docs/how-to-deploy-cp4waiops-36.md

Signed-off-by: Louise Roberts <louiseroberts@uk.ibm.com>
https://github.ibm.com/katamari/dev-issue-tracking/issues/43196

Docs edits for #43196
